name: Server Deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          bun install
          
      - name: Build
        run: |
          bun run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: false
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy bitespeed-backend-assignment \
              --source=. \
              --allow-unauthenticated \
              --region=${{ secrets.GCP_REGION }} \